### ISSUE TITLE
Any plan to extend it for ACM200 device ?

### ISSUE THREAD

**Issue by vincegre** [foxy82/pyblustream#1]
Hi

Do you plan to update the lib to manage also the ACM200 used for the HDMI Av Over IP matrixes ?

Thanks

Vincèn

**Comment by foxy82** [comment]
I don't have one of those devices so I don't have anything to test against.

**Comment by vincegre** [comment]
> I don't have one of those devices so I don't have anything to test against.

I understand, thanks for answer ;)
